### ISSUE TITLE
Edge failure

### ISSUE THREAD

**Issue by Resonanz** [spinningarrow/zoom-vanilla.js#40] opened 2018-04-12 07:02 UTC
Just visited the bottom image on this website:

http://themes.getbootstrap.com/preview/?theme_id=1703&show_new=

and clicked to enalrge, then decrease, but mouse could no longer clock on anything and magnifying glass with "-" symbol remained.

**Comment by spinningarrow** [comment] 2018-04-12 07:51
Thanks for reporting this! The demo page for this repo appears to have that issue on Edge as well. I'll look into it.

**Comment by spinningarrow** [comment] 2019-05-16 12:07
Closing as this should be fixed.

**Closed by spinningarrow** 2019-05-16 12:07 UTC
Labels: bug

**Comment by sixpixel** [comment] 2020-05-18 21:52
Hi @spinningarrow I'm running into this issue on the latest Microsoft Edge Chromium and Google Chrome builds. Appears to work fine in Firefox and Safari, might be a new Chromium bug?

**Comment by spinningarrow** [comment] 2020-05-19 08:21
@sixpixel thanks for reporting! I haven't had the chance to check it on Edge Chromium yet but I'm unable to reproduce it on the latest Google Chrome. I'm on version 81.0.4044.138 (macOS).

Which version of google chrome do you see this issue in? And does the issue also happen on the demo page of this library (https://code.sahil.me/zoom-vanilla.js/)?

**Comment by sixpixel** [comment] 2020-05-21 20:33
@spinningarrow Hi sorry, I've been away from my PC for a couple of days. The versions I found the issue on are Microsoft Edge Version 81.0.416.77 (latest stable) and Chrome Canary Version  85.0.4149.2 both on Windows 10. The issue does also happen on your demo page.
